export const FETCH_ALL_TIME_POPULAR_ANIME_START =
  'FETCH_ALL_TIME_POPULAR_ANIME_START';
export const FETCH_ALL_TIME_POPULAR_ANIME_SUCCESS =
  'FETCH_ALL_TIME_POPULAR_ANIME_SUCCESS';
export const FETCH_ALL_TIME_POPULAR_ANIME_FAILURE =
  'FETCH_ALL_TIME_POPULAR_ANIME_FAILURE';
