export const FETCH_UPCOMING_ANIME_START = 'FETCH_UPCOMING_ANIME_START';
export const FETCH_UPCOMING_ANIME_SUCCESS = 'FETCH_UPCOMING_ANIME_SUCCESS';
export const FETCH_UPCOMING_ANIME_FAILURE = 'FETCH_UPCOMING_ANIME_FAILURE';
