export const FETCH_POPULAR_ANIME_MOVIE_START =
  'FETCH_POPULAR_ANIME_MOVIE_START';
export const FETCH_POPULAR_ANIME_MOVIE_SUCCESS =
  'FETCH_POPULAR_ANIME_MOVIE_SUCCESS';
export const FETCH_POPULAR_ANIME_MOVIE_FAILURE =
  'FETCH_POPULAR_ANIME_MOVIE_FAILURE';
