export const FETCH_AIRING_ANIME_START = 'FETCH_AIRING_ANIME_START';
export const FETCH_AIRING_ANIME_SUCCESS = 'FETCH_AIRING_ANIME_SUCCESS';
export const FETCH_AIRING_ANIME_FAILURE = 'FETCH_AIRING_ANIME_FAILURE';
